### ISSUE TITLE
Default Date header uses UTC instead of local time

### ISSUE THREAD

**Issue by mscha** [retupmoca/p6-Email-Simple#11]
When you don't specify a Date header, one is provided for you with the current time.
However, the time zone used in this header is UTC, which is not incorrect, but a bit unusual: it makes more sense to use the local timezone.

The reason is the following code:

    if !($header-object.header('Date')) {
        $header-object.header-set('Date', DateTime::Format::RFC2822.to-string(DateTime.new(now)));
    }

If this is changed to the slightly cleaner:

    if !($header-object.header('Date')) {
        $header-object.header-set('Date', DateTime::Format::RFC2822.to-string(DateTime.now));
    }

the local timezone is used in the header.

(To make things worse, the time zone indicator for UTC, `U`, is incorrect, but that's a [bug in DateTime::Format::RFC2822](https://github.com/supernovus/perl6-datetime-format/issues/15).)

**Comment by retupmoca** [comment]
This is adjusted (using your suggestion) in the latest version.
