### ISSUE TITLE
Email::Simple::Headers should support header pairs

### ISSUE THREAD

**Issue by mscha** [retupmoca/p6-Email-Simple#12]
Currently, `Email::Simple::Headers` expects headers in an array of arrays, or optionally in one single array.  But it does not support the more Perl6-ish  syntax of using pairs.
Please add support for this, so we can use:

```perl6
my $new = Email::Simple.create(header => [:To<mail@example.com>,
                                          :From<me@example.com>,
                                          :Subject<test>],
                               body => 'This is a test.');
```

**Comment by retupmoca** [comment]
Header pairs now work in version 2.1

**Comment by vendethiel** [comment]
Code actually matches on `[0]` being a `Pair`. Could it also check for `Associative`, so that `:header{}` can work?
